### ISSUE TITLE
Dowloaded files directory

### ISSUE THREAD

**Issue by enderahmetyurt** [muratbsts/tors#1]
What's the directory by default? Can we change the default one?

**Comment by muratbsts** [comment]
@enderahmetyurt there isn't a directory option. The default directory is current/working directory. Do you think this is necessary?

**Comment by enderahmetyurt** [comment]
I guess I can call the gem from Project directory. I can prefer to download the file to Downloads/Movies/. It should be set up.

**Comment by muratbsts** [comment]
Hmm. You are right. Next minor version must have an option as `-d (--directory)`. Thanks for your thoughts.

**Comment by MuhammetDilmac** [comment]
If I give you permission, I add this feature :)

**Comment by muratbsts** [comment]
I'm honored :). You can feel free @MuhammetDilmac I'm waiting your PR.

**Comment by muratbsts** [comment]
Closed with #2
