### ISSUE TITLE
Turkish char. problem

### ISSUE THREAD

**Issue by enderahmetyurt** [muratbsts/tors#9]
Although I just want to list movie which includes Turkish characters, i get the error about ascii char.
<img width="1266" alt="screen shot 2017-09-02 at 15 58 42" src="https://user-images.githubusercontent.com/447588/29995677-bfb83578-8ff7-11e7-8d66-3bf09214cac0.png">

**Comment by muratbsts** [comment]
Thanks for report @enderahmetyurt
I'll fix it with URI encode or escape.

**Comment by muratbsts** [comment]
Fixed with https://github.com/muratbsts/tors/commit/20ad569897c397a92ad5c3abc108339584af5fbd
